// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need an unpooled connection: a transaction-mode pooler cannot
    // run DDL, and a migration that blocks on it hangs instead of failing.
    // Falls back to DATABASE_URL so a host that only sets one variable (a local
    // machine, or `prisma generate` during the build) still works.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
